# FROM mysql/mysql-server:8.0

# ENV MYSQL_DATABASE=laravel \
#   MYSQL_USER=mizo \
#   MYSQL_PASSWORD=mizomizo1 \
#   MYSQL_ROOT_PASSWORD=mizoguchi \
#   TZ=Asia/Tokyo

# COPY ./my.cnf /etc/my.cnf
# RUN chmod 644 /etc/my.cnf
